### ISSUE TITLE
(wiki) incorrect sensor names used in `integration` sensor examples

### ISSUE THREAD

**Issue by an4tomic1** [luuuis/hass_wibeee#49]
Following the sensors example, custom template sensor miss the "name" field. Without the "name" field, they're gonna be generated as "sensor.template_grid..."
<img width="349" alt="image" src="https://user-images.githubusercontent.com/11066858/198841092-28da6a72-2fc0-44ec-9edb-12cfa339a920.png">

this leads to a fail when creating "Integration - Riemann sum integral" sensors, as they search for "sensor.grid..."
![image](https://user-images.githubusercontent.com/11066858/198841151-49180463-3d05-45b8-bdfd-def935638cd4.png)

Propossed code to solution it's just add name field to template example:

```
template:
  sensor:
    - name: grid_import_export_power
      unique_id: grid_import_export_power
      device_class: power
      unit_of_measurement: 'W'
      state_class: measurement
      state: >-
        {% if states('sensor.wibeee_phase4_power_factor') | float < 0 %}
          {{ states('sensor.wibeee_phase4_active_power') | float * -1 | round(0) }}
        {% else %}
          {{ states('sensor.wibeee_phase4_active_power') | float | round(0) }}
        {% endif %}
      availability: "{{ not states('sensor.wibeee_phase4_active_power') in ('unavailable', 'unknown') and not states('sensor.wibeee_phase4_power_factor') in ('unavailable', 'unknown') }}"
      attributes:
        friendly_name: "Grid import(+) or export(-) power"
    - name: grid_import_power
      unique_id: grid_import_power
      device_class: power
      unit_of_measurement: 'W'
      state_class: measurement
      state: "{{ [states('sensor.template_grid_import_export_power') | float, 0] | max | round(0) }}"
      availability: "{{ not states('sensor.template_grid_import_export_power') in ('unavailable', 'unknown') }}"
      attributes:
        friendly_name: "Grid import power"
    - name: grid_export_power
      unique_id: grid_export_power
      device_class: power
      unit_of_measurement: 'W'
      state_class: measurement
      state: "{{ [states('sensor.template_grid_import_export_power') | float, 0] | min | abs | round(0) }}"
      availability: "{{ not states('sensor.template_grid_import_export_power') in ('unavailable', 'unknown') }}"
      attributes:
        friendly_name: "Grid export power"
```
